version: 1
formatters:
  simple:
    format: '%(levelname)s:%(module)s:%(asctime)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    mode: 'w'
    filename: logs/log.log
  email:
    class: logging.handlers.SMTPHandler
    mailhost: smtp.xs4all.nl
    fromaddr: mnz@xs4all.nl
    toaddrs: mnz@xs4all.nl
    subject: 'TFS log: '
    level: CRITICAL
    formatter: simple
loggers:
  tfsfile:
    level: DEBUG
    handlers: [file]
  tfsmail:
    level: DEBUG
    handlers: [email]
root:
  level: INFO
  handlers: [file, email]
